# Makefile generated by BNFC.

# List of goals not corresponding to file names.

.PHONY : all clean distclean test

# Default goal.

all : TestQwerty main
debug : TestQwerty maindebug


test: testgood testbad

testgood: all
	for file in good/* ;\
	do \
		echo -e "\n    *** STARTING " $$file " ***" ; \
		timeout 2 ./interpreter "$$file" ; \
	done

testbad: all
	for file in bad/* ;\
	do \
		echo -e "\n    *** STARTING " $$file " ***" ; \
		timeout 2 ./interpreter "$$file" ; \
	done


main: main.hs
	ghc --make main.hs -o interpreter -igrammar
maindebug: main.hs
	ghc --make main.hs -o interpreter -igrammar -prof -fprof-auto-calls

# Rules for building the parser.

ErrM.hs LexQwerty.x PrintQwerty.hs ParQwerty.y TestQwerty.hs : qwerty.cf
	bnfc --haskell qwerty.cf

%.hs : %.y
	happy --ghc --coerce --array --info $<

%.hs : %.x
	alex --ghc $<

TestQwerty : TestQwerty.hs ErrM.hs LexQwerty.hs ParQwerty.hs PrintQwerty.hs
	ghc --make $< -o $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsQwerty.hs AbsQwerty.hs.bak ComposOp.hs ComposOp.hs.bak DocQwerty.txt DocQwerty.txt.bak ErrM.hs ErrM.hs.bak LayoutQwerty.hs LayoutQwerty.hs.bak LexQwerty.x LexQwerty.x.bak ParQwerty.y ParQwerty.y.bak PrintQwerty.hs PrintQwerty.hs.bak SharedString.hs SharedString.hs.bak SkelQwerty.hs SkelQwerty.hs.bak TestQwerty.hs TestQwerty.hs.bak XMLQwerty.hs XMLQwerty.hs.bak ASTQwerty.agda ASTQwerty.agda.bak ParserQwerty.agda ParserQwerty.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak qwerty.dtd qwerty.dtd.bak TestQwerty LexQwerty.hs ParQwerty.hs ParQwerty.info ParDataQwerty.hs Makefile
	

# EOF
