{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintQwerty.
--   Generated by the BNF converter.

module PrintQwerty where

import qualified AbsQwerty
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else ' ':s)

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsQwerty.Ident where
  prt _ (AbsQwerty.Ident i) = doc (showString i)

instance Print AbsQwerty.Program where
  prt i e = case e of
    AbsQwerty.MainProg fndefs -> prPrec i 0 (concatD [prt 0 fndefs])

instance Print AbsQwerty.FnDef where
  prt i e = case e of
    AbsQwerty.TopDef type_ id args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id, prt 0 args, prt 0 block])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsQwerty.Args where
  prt i e = case e of
    AbsQwerty.FunArgs args -> prPrec i 0 (concatD [doc (showString "("), prt 0 args, doc (showString ")")])

instance Print [AbsQwerty.FnDef] where
  prt = prtList

instance Print AbsQwerty.Arg where
  prt i e = case e of
    AbsQwerty.FunArg type_ id -> prPrec i 0 (concatD [prt 0 type_, prt 0 id])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsQwerty.Arg] where
  prt = prtList

instance Print AbsQwerty.Block where
  prt i e = case e of
    AbsQwerty.ScopeBlock stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsQwerty.Stmt] where
  prt = prtList

instance Print AbsQwerty.Stmt where
  prt i e = case e of
    AbsQwerty.Empty -> prPrec i 0 (concatD [doc (showString ";")])
    AbsQwerty.BStmt block -> prPrec i 0 (concatD [prt 0 block])
    AbsQwerty.NestFunc fndef -> prPrec i 0 (concatD [prt 0 fndef])
    AbsQwerty.Decl type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    AbsQwerty.Ass id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsQwerty.Incr id -> prPrec i 0 (concatD [prt 0 id, doc (showString "++"), doc (showString ";")])
    AbsQwerty.Decr id -> prPrec i 0 (concatD [prt 0 id, doc (showString "--"), doc (showString ";")])
    AbsQwerty.Assert expr -> prPrec i 0 (concatD [doc (showString "assert"), prt 0 expr, doc (showString ";")])
    AbsQwerty.Ret expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsQwerty.Cond expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsQwerty.CondElse expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    AbsQwerty.While expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsQwerty.SExp expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print AbsQwerty.Item where
  prt i e = case e of
    AbsQwerty.NoInit id -> prPrec i 0 (concatD [prt 0 id])
    AbsQwerty.Init id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsQwerty.Item] where
  prt = prtList

instance Print AbsQwerty.Type where
  prt i e = case e of
    AbsQwerty.TInt -> prPrec i 0 (concatD [doc (showString "int")])
    AbsQwerty.TStr -> prPrec i 0 (concatD [doc (showString "string")])
    AbsQwerty.TBool -> prPrec i 0 (concatD [doc (showString "boolean")])
    AbsQwerty.TVoid -> prPrec i 0 (concatD [doc (showString "void")])
    AbsQwerty.TFun types type_ -> prPrec i 0 (concatD [doc (showString "(("), prt 0 types, doc (showString ")"), doc (showString "=>"), prt 0 type_, doc (showString ")")])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsQwerty.Type] where
  prt = prtList

instance Print AbsQwerty.Expr where
  prt i e = case e of
    AbsQwerty.EVar id -> prPrec i 6 (concatD [prt 0 id])
    AbsQwerty.ELambda args block -> prPrec i 6 (concatD [prt 0 args, doc (showString "=>"), prt 0 block])
    AbsQwerty.ELitInt n -> prPrec i 6 (concatD [prt 0 n])
    AbsQwerty.ELitTrue -> prPrec i 6 (concatD [doc (showString "true")])
    AbsQwerty.ELitFalse -> prPrec i 6 (concatD [doc (showString "false")])
    AbsQwerty.EApp expr exprs -> prPrec i 6 (concatD [prt 0 expr, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsQwerty.EString str -> prPrec i 6 (concatD [prt 0 str])
    AbsQwerty.Neg expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsQwerty.Not expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    AbsQwerty.EMul expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsQwerty.EAdd expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsQwerty.ERel expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsQwerty.EAnd expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    AbsQwerty.EOr expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = concatD []
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [AbsQwerty.Expr] where
  prt = prtList

instance Print AbsQwerty.AddOp where
  prt i e = case e of
    AbsQwerty.Plus -> prPrec i 0 (concatD [doc (showString "+")])
    AbsQwerty.Minus -> prPrec i 0 (concatD [doc (showString "-")])

instance Print AbsQwerty.MulOp where
  prt i e = case e of
    AbsQwerty.Times -> prPrec i 0 (concatD [doc (showString "*")])
    AbsQwerty.Div -> prPrec i 0 (concatD [doc (showString "/")])
    AbsQwerty.Mod -> prPrec i 0 (concatD [doc (showString "%")])

instance Print AbsQwerty.RelOp where
  prt i e = case e of
    AbsQwerty.LTH -> prPrec i 0 (concatD [doc (showString "<")])
    AbsQwerty.LE -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsQwerty.GTH -> prPrec i 0 (concatD [doc (showString ">")])
    AbsQwerty.GE -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsQwerty.EQU -> prPrec i 0 (concatD [doc (showString "==")])
    AbsQwerty.NE -> prPrec i 0 (concatD [doc (showString "!=")])

